### ISSUE TITLE
Using Websocket Client to send high speed binary data to webserver or Cloud

### ISSUE THREAD

**Issue by williamesp2015** [krzychb/EspToCloud#1]
I am thinking of high speed transmitting binary data to own webserver to display data like ESPScope. Have you an example?
Thank you

**Comment by krzychb** [comment]
Hi @williamesp2015,

What speed do you mean in samples / sec?
What would be the sample size to transmit?
Do you mean sending the data out just for displaying?

Krzysztof

**Comment by williamesp2015** [comment]
HI @krzychb 
I need to send out 20 bytes*200 times/sec binary data and display on a chart on webserver+OTA+set ESP config by Internet connection. I found a very good example named Websocket Client fast:
https://github.com/u0078867/Arduino-Websocket-Fast/tree/master/examples/SocketIOClient_ISP8266_Demo
but it does not work on ESP8266.

Thank you

**Comment by krzychb** [comment]
Hi @williamesp2015,

The example you mentioned above indeed looks like broken.

I did quick and dirty test and the time to request and receive 20 bytes of data using [ESPScopeA0](https://github.com/krzychb/EspScopeA0) application is about 16ms. This means that as it is now, I can achieve about 60 samples per second.

Unfortunately this is far away from 200 samples / second you need.

Currently I do not have time to do more detailed testing because of another project am working on.
I plan to return to updating [ESPScopeA0](https://github.com/krzychb/EspScopeA0) repository in next couple of weeks.

Krzysztof
